[package]
name = "cxx-test"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"
sprs = "0.11.3"
ndarray = "0.16.1"
rand = "0.8.5"
ndarray-rand = "0.15.0"
fasthash = "0.4.0"

[build-dependencies]
cxx-build = "1.0"
